### ISSUE TITLE
Add a "delete song" button somewhere

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#17]
Add a "delete song" button somewhere. Currently, it seems you can't delete a song ? (without delete the file on the server).

**Comment by bloodybowlers** [comment]
Added in f16cd68ad1b1a2e1329ea758eababb5b0ebac68e

**Comment by Louis-coding-UGNG** [comment]
When UGNG is installed in a subdirectory, the delete button kicks you back to domain root instead of the songbook directory.
I would assume the reason in this line of code:
https://github.com/bloodybowlers/UkeGeeks-ng/blob/f16cd68ad1b1a2e1329ea758eababb5b0ebac68e/src/js/editor/ugsEditorPlus.deleteSong.js#L106

**Comment by Louis-coding-UGNG** [comment]
it seems changing the location to
`document.location.href = './'; `
already does the trick
