### ISSUE TITLE
chord wrapper is not beneath text but above initially

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#33]
introduced with #20 
https://github.com/bloodybowlers/UkeGeeks-ng/blob/c29f6c10a08476c0231e10c1ee9f3610c702ce57/ugsphp/views/song-editable.php#L34
the _div_ seems to need the same classes as the _aside_, should be initially
`<div id="ukeChordsCanvasWrapper" class="ugs-diagrams-wrap ugs-grouped">`
and after scrolling
`<div id="ukeChordsCanvasWrapper" class="ugs-diagrams-wrap ugs-grouped chordsAlwaysOnTop">`

Might even be these classes should be on the _div_ rather than the _aside_ (duplication doesn't seem to hurt though)...

**Comment by bloodybowlers** [comment]
Sorry I don't get it. How do you reproduce the bug ? Do you have a screenshot ?
I tried on my side but everything looks normal (using Chrome here) ?

**Comment by Louis-coding-UGNG** [comment]
Looks similar in Edge, Chrome  and FF (Win 10).

That's how it looks currently (the chord box stays on top left when scrolling down)
![2019-08-04](https://user-images.githubusercontent.com/53580683/62428678-65f7c680-b704-11e9-9f87-70980eb5eb72.png)

That's how it looks with the class copied from the _aside_ to the _div_
![2019-08-04 (3)](https://user-images.githubusercontent.com/53580683/62428682-7314b580-b704-11e9-82c0-43b8749b7e2a.png)

(URL is a demo site with default credentials and lang=DE)

**Comment by bloodybowlers** [comment]
I see now.

This is intended behavior. If you want the chords above (as I do) you should set it with the display menu (or in the settings.js file for it to be permanent : "diagramPosition": "top").
I have mine set to "top" and it works.

If chords are set to the left, then they stay there because it is where the user wants them.

This was not introduced with #20, it worked like that before  ?

**Edit : Whaaaaaaaaaa....  I see the huge line breaks you have before the lyrics.... I don't have those on my install... I'll take a look :P**

**Comment by bloodybowlers** [comment]
88f71710786e9f430d744178908ecbb2a0a2f31f should fix it :)

**Comment by Louis-coding-UGNG** [comment]
Almost.....
The floating box should IMHO **always** appear as soon as the first row of diagrams disappeared. Right now the diagrams only start to flow once the whole block disappeared - which is not so nice when you have 4 rows of diagrams on the side...
In other words: trigger should only be diagram height, not chord box height.

**Comment by bloodybowlers** [comment]
> trigger should only be diagram height, not chord box height.

Yep, you are right.
