### ISSUE TITLE
deleting a song doesn't close the song tab where it was opened

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#59]
with `const openSongInNewTab = true;`, deleting a song does not close the new tab but returns to the songbook index in the new tab - leading to two open tabs with the songbook index (one with the old version, one with the new version and one song less)

**Comment by bloodybowlers** [comment]
Yep, same goes for "add new song" feature.

I made a git branch on my machine with the "close tab" feature and it works. Only problem left is :  
you can't launch a refresh in another tab. So when you delete or create a song, it won't be refreshed.  

So, what's best : no closing, or no refresh ? What do you think ?

**Comment by Louis-coding-UGNG** [comment]
> So, what's best : no closing, or no refresh ? What do you think ?

Easy answer: No refresh.
We already have the reindex button, so it should be sufficient to add a little note into the `confirm_delete_song` text, something like "Pls refresh your songbook index manually after all deletions are done"

**Comment by bloodybowlers** [comment]
~~The index **IS** refreshed by the delete or adding (ie : reindex is happening). It's just the **display** in the other tab, with the song list, that isn't (you can't control other tab in js).~~ no ! it's not...
Anyway, I'll close the tab on delete, and on "new song", no problem.

**Comment by bloodybowlers** [comment]
Should now be fixed with c6dc9876b8b2a13b835f27284724497790855aaf and 6e407020848b69e74c9e51c2ff5bbb5cdc177b38

No current solution for the refreshing problem ~~, but that's not a very big deal (the re-indexing is happening anyway)...~~ re-indexing is **not** happening... we need to show a message to the user :(

**Edit** : It seems it's reindexing... but not always ? (cache problem of webhost ?) Needs more testing...
